a=int(input("Enter the a value is::"))
b=int(input("Enter the b value is::"))
print("Addition::",a+b)
print("Mul::",a*b)
print("Lessthan::",(a<b))
print("Greaterthan::",(a>b))
print("Equalto::",(a==b))
print("LogicalOperator")
print("LogicalAND::",(a>b)and(b<a))
print("LogicalOR::",(a>b)or(b>a))
print("LogicalNOT::",not(a>b))
